CREATE TABLE "Users" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Hash"	TEXT NOT NULL,
	"UserName"	TEXT NOT NULL
);

CREATE TABLE "Rooms" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT NOT NULL
);

CREATE TABLE "Reservations" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"RoomId"	INTEGER NOT NULL,
	"UserId"	INTEGER NOT NULL,
	"StartDate"	DATETIME NOT NULL,
	"EndDate"	DATETIME NOT NULL
);

INSERT INTO Rooms (Name) VALUES ('ROOM A');
INSERT INTO Rooms (Name) VALUES ('ROOM B');
INSERT INTO Rooms (Name) VALUES ('ROOM C');