CREATE TABLE Users (
	Id BIGINT NOT NULL PRIMARY KEY,
	Hash VARCHAR(32) NOT NULL,
	UserName VARCHAR(255) NOT NULL,
);

CREATE TABLE Rooms (
	Id BIGINT NOT NULL PRIMARY KEY,
	Name VARCHAR(1000) NOT NULL,
);

CREATE TABLE Reservations (
	Id BIGINT NOT NULL PRIMARY KEY,
	StartDate BIGINT NOT NULL,
	EndDate BIGINT NOT NULL,
	RoomId BIGINT NOT NULL,
	UserId BIGINT NOT NULL,
);


INSERT INTO Rooms (Name) VALUES ('ROOM A');
INSERT INTO Rooms (Name) VALUES ('ROOM B');
INSERT INTO Rooms (Name) VALUES ('ROOM C');